name: Book Tracker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov allure-pytest

    - name: Run tests
      run: |
        # Установка переменной окружения для Python
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
        
        # Запуск Flask в фоне с тестовой БД
        python -m book_tracker.app &
        
        # Ждем запуска сервера
        sleep 5
        
        # Запуск тестов
        pytest tests/ --cov=book_tracker --alluredir=./allure-results
        
        # Остановка Flask
        pkill -f "python -m book_tracker.app"

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results/
        if-no-files-found: ignore